---
title: "NFL Injuries: Modeling"
author:
  - name: "Samantha Erne ^[Email: ernesm@miamioh.edu]"
    affiliation: Farmer School of Business, Miami University
  - name: "Brendan Beattie ^[Email: beattibs@miamioh.edu]"
    affiliation: Farmer School of Business, Miami University
  - name: "Jake Holroyd 2 ^[Email: holroyjm@miamioh.edu]"
    affiliation: Farmer School of Business, Miami University
  - name: "Peter Walsh ^[Email: walshpd2@miamioh.edu]"
    affiliation: Farmer School of Business, Miami University
  - name: "Dr. Fadel Megahed ^[Email: fmegahed@miamioh.edu]"
    affiliation: Farmer School of Business, Miami University
date: 'Date: `r Sys.Date()`'
output:
  html_document:
    code_folding: show
    code_download: TRUE
    number_sections: FALSE
    paged_df: TRUE
    toc: TRUE
    toc_float: TRUE
    theme: readable
---
NFL Injuries: Modeling

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      progress = FALSE,
                      verbose = TRUE,
                      cache = TRUE)

```

# Required R Packages
```{r}
if(require(pacman)== FALSE) install.packages("pacman")
pacman::p_load(tidyverse, 
               lubridate,# for making a column name from row 1
               magrittr, rvest, nflreadr, nflfastR, stringr, dplyr, caret, MuMIn, parallel, foreach, doParallel)
```

# Best Overall Model (No Stadium)

```{r best_overall_model_no_stadium_var}
game_injury_player_update1 = 
  read_csv("final_files/game_injury_player_2019_2020_complete_update_vegas_weeks_bucketed_2.csv")

game_injury_player_update1$weeks_bucketed = as.character(game_injury_player_update1$weeks_bucketed)
game_injury_player_update1$season = as.character(game_injury_player_update1$season)

## Reducing the dimensions present in the stadium variable
df_subset <- game_injury_player_update1 %>%  
  select(game_id, num_injuries,
         #stadium, 
         dome, surface_type,season,
         weeks_bucketed, distance_miles_away,
         HOME_day_since_last_game,AWAY_day_since_last_game,Avg_Feels_Like,
         Avg_Percipitation_Prob_Percent, Avg_Humidity_Percent,
         spread_line, total_line) %>% 
  unique() %>% 
  mutate(num_injuries = as.integer(num_injuries))

df_subset <- df_subset %>% 
  select(-game_id) %>% 
  mutate_if(is.character, as.factor)


univ_poisson = glm(num_injuries ~ ., data = df_subset, na.action = na.pass, family="poisson")
#summary(univ_poisson)

dredge_models_univ = MuMIn::dredge(univ_poisson)


## dredge_models_univ as a list for easier manipulation
all_models_univ = MuMIn::get.models(dredge_models_univ, subset = T)
saveRDS(all_models_univ, "final_files/rds_models/all_models_no_stadium.rds")

dredge_models_univ$BIC = purrr::map_dbl(.x = all_models_univ, .f = BIC)
dredge_models_univ$AIC = purrr::map_dbl(.x = all_models_univ, .f = AIC)
dredge_models_univ$rsq =  purrr::map_dbl(.x = all_models_univ, .f = rsq::rsq, adj= T) 

dredge_models_univ %>% dplyr::arrange(desc(rsq)) %>% head()
which.min(dredge_models_univ$BIC)
min(dredge_models_univ$BIC)
which.max(dredge_models_univ$rsq)
max(dredge_models_univ$rsq)

best_univ_model = MuMIn::get.models(dredge_models_univ, subset = T)[[20]]
summary(best_univ_model)
rsq::rsq(best_univ_model, adj = T)
BIC(best_univ_model)
pchisq(best_univ_model$deviance, best_univ_model$df.residual, lower.tail = FALSE)
saveRDS(best_univ_model, file = "final_files/rds_models/best_univ_model_no_stadium.rds")

best_univ_model_rds_no_stadium = readRDS("final_files/rds_models/best_univ_model_no_stadium.rds")
# extract the model summary information
best_univ_model_summ_no_stadium <- summary(best_univ_model_rds_no_stadium)
coefficients <- coef(best_univ_model_summ_no_stadium)
pvalues <- summary(best_univ_model_rds_no_stadium)$coefficients[, 4]
std_errors <- summary(best_univ_model_rds_no_stadium)$coefficients[, 2]
z_score <- summary(best_univ_model_rds_no_stadium)$coefficients[,3]
library(lmtest)
# add AIC, BIC, AICc and adj-R2
aic <- AIC(best_univ_model_rds_no_stadium)
bic <- BIC(best_univ_model_rds_no_stadium)
aic_c <- AICc(best_univ_model_rds_no_stadium)
adj_r_sq <- rsq::rsq(best_univ_model_rds_no_stadium, adj = T)
# create the table
table <- data.frame(Coefficient = coefficients, `Std. Error` = std_errors, `P-value` = pvalues, `z value` = z_score)
sapply(table, class)
table$Coefficient <- round(table$Coefficient.Estimate, 4)
table$StdError <- round(table$Coefficient.Std..Error, 4)
table$Pvalue <- format.pval(table$P.value, digits = 2)
table$z_score <-round(table$Coefficient.z.value, digits = 2)

table = table[,-c(1,2,3,4,5,6,7)]


table <- cbind(table, adjr2 = adj_r_sq, BIC = bic, AIC = aic, AICc = aic_c)




library(kableExtra)
# print the table
kable(table, caption = "Best Univariate (No Stadium) Poisson Regression Model") %>%
  kable_styling()

```

# Best Overall Model (No Surface)

```{r}
game_injury_player_update_no_surf = 
  read_csv("final_files/game_injury_player_2019_2020_complete_update_vegas_weeks_bucketed_2.csv")

game_injury_player_update_no_surf$weeks_bucketed = as.character(game_injury_player_update_no_surf$weeks_bucketed)
game_injury_player_update_no_surf$season = as.character(game_injury_player_update_no_surf$season)

## Reducing the dimensions present in the stadium variable
df_subset1 <- game_injury_player_update_no_surf %>%  
  select(game_id, num_injuries,
         stadium, 
         dome, 
         #surface_type,
         season,
         weeks_bucketed, distance_miles_away,
         HOME_day_since_last_game,AWAY_day_since_last_game,Avg_Feels_Like,
         Avg_Percipitation_Prob_Percent, Avg_Humidity_Percent,
         spread_line, total_line) %>% 
  unique() %>% 
  mutate(num_injuries = as.integer(num_injuries))

df_subset1 <- df_subset1 %>% 
  select(-game_id) %>% 
  mutate_if(is.character, as.factor)


univ_poisson1 = glm(num_injuries ~ ., data = df_subset1, na.action = na.pass, family="poisson")
#summary(univ_poisson1)

dredge_models_univ1 = MuMIn::dredge(univ_poisson1)


## dredge_models_univ as a list for easier manipulation
all_models_univ1 = MuMIn::get.models(dredge_models_univ1, subset = T)
saveRDS(all_models_univ1, "final_files/rds_models/all_models_main_no_surface.rds")

dredge_models_univ1$BIC = purrr::map_dbl(.x = all_models_univ1, .f = BIC)
dredge_models_univ1$AIC = purrr::map_dbl(.x = all_models_univ1, .f = AIC)
dredge_models_univ1$rsq =  purrr::map_dbl(.x = all_models_univ1, .f = rsq::rsq, adj= T) 

dredge_models_univ1 %>% dplyr::arrange(desc(BIC)) %>% head()
which.min(dredge_models_univ1$BIC)
min(dredge_models_univ1$BIC)

best_univ_model1 = MuMIn::get.models(dredge_models_univ1, subset = T)[[3]]
summary(best_univ_model1)
rsq::rsq(best_univ_model1, adj = T)
pchisq(best_univ_model1$deviance, best_univ_model1$df.residual, lower.tail = FALSE)
saveRDS(best_univ_model1, file = "final_files/rds_models/best_univ_model_no_surface.rds")

best_univ_model_rds_no_surf = readRDS("final_files/rds_models/best_univ_model_no_surface.rds")
# extract the model summary information
best_univ_model_summ_no_surf <- summary(best_univ_model_rds_no_surf)
coefficients <- coef(best_univ_model_summ_no_surf)
pvalues <- summary(best_univ_model_rds_no_surf)$coefficients[, 4]
std_errors <- summary(best_univ_model_rds_no_surf)$coefficients[, 2]
z_score <- summary(best_univ_model_rds_no_surf)$coefficients[,3]
library(lmtest)
# add AIC, BIC, AICc and adj-R2
aic <- AIC(best_univ_model_rds_no_surf)
bic <- BIC(best_univ_model_rds_no_surf)
aic_c <- AICc(best_univ_model_rds_no_surf)
adj_r_sq <- rsq::rsq(best_univ_model_rds_no_surf, adj = T)
# create the table
table <- data.frame(Coefficient = coefficients, `Std. Error` = std_errors, `P-value` = pvalues, `z value` = z_score)
sapply(table, class)
table$Coefficient <- round(table$Coefficient.Estimate, 4)
table$StdError <- round(table$Coefficient.Std..Error, 4)
table$Pvalue <- format.pval(table$P.value, digits = 2)
table$z_score <-round(table$Coefficient.z.value, digits = 2)

table = table[,-c(1,2,3,4,5,6,7)]


table <- cbind(table, adjr2 = adj_r_sq, BIC = bic, AIC = aic, AICc = aic_c)




library(kableExtra)
# print the table
kable(table, caption = "Best Univariate (No Surface) Poisson Regression Model") %>%
  kable_styling()

```


# Best Lower Body (No Stadium) Model
```{r}
df_lb = read_csv("final_files/game_injury_player_2019_2020_complete_update_vegas_weeks_bucketed_2_lb.csv")

df_lb$weeks_bucketed = as.character(df_lb$weeks_bucketed)
df_lb$season = as.character(df_lb$season)


df_lb_subset <- df_lb %>%  
  select(game_id, num_injuries,
         #stadium, 
         dome, 
         surface_type,
         season,
         weeks_bucketed, distance_miles_away,
         HOME_day_since_last_game,AWAY_day_since_last_game,Avg_Feels_Like,
         Avg_Percipitation_Prob_Percent, Avg_Humidity_Percent,
         spread_line, total_line) %>% 
  unique() %>% 
  mutate(num_injuries = as.integer(num_injuries))#,


df_lb_subset <- df_lb_subset %>% 
  select(-game_id) %>% 
  mutate_if(is.character, as.factor)


lower_body_poisson = glm(num_injuries ~ ., data = df_lb_subset, na.action = na.pass, family="poisson")
summary(lower_body_poisson)

# Examining goodness of fit
dredge_models_lb = MuMIn::dredge(lower_body_poisson)

all_models_lb = MuMIn::get.models(dredge_models_lb, subset = T)
saveRDS(all_models_lb, "final_files/rds_models/all_models_lb_no_stadium.rds")


dredge_models_lb$BIC = purrr::map_dbl(.x = all_models_lb, .f = BIC)
dredge_models_lb$AIC = purrr::map_dbl(.x = all_models_lb, .f = AIC)
dredge_models_lb$rsq =  purrr::map_dbl(.x = all_models_lb, .f = rsq::rsq, adj= T) 

dredge_models_lb %>% dplyr::arrange(desc(BIC)) %>% head()

which.min(dredge_models_lb$BIC)
min(dredge_models_lb$BIC)
max(dredge_models_lb$rsq)
which.max(dredge_models_lb$rsq)

best_lb_model = MuMIn::get.models(dredge_models_lb, subset = T)[[16]]
summary(best_lb_model)
rsq::rsq(best_lb_model, adj = T)
BIC(best_lb_model)
pchisq(best_lb_model$deviance, best_lb_model$df.residual, lower.tail = FALSE)
saveRDS(best_lb_model, file = "final_files/rds_models/best_lb_model_no_stadium.rds")

best_lb_model_rds_no_stadium = readRDS("final_files/rds_models/best_lb_model_no_stadium.rds")
# extract the model summary information
best_lb_model_summ_no_stadium <- summary(best_lb_model_rds_no_stadium)
coefficients <- coef(best_lb_model_summ_no_stadium)
pvalues <- summary(best_lb_model_rds_no_stadium)$coefficients[, 4]
std_errors <- summary(best_lb_model_rds_no_stadium)$coefficients[, 2]
z_score <- summary(best_lb_model_rds_no_stadium)$coefficients[,3]
library(lmtest)
# add AIC, BIC, AICc and adj-R2
aic <- AIC(best_lb_model_rds_no_stadium)
bic <- BIC(best_lb_model_rds_no_stadium)
aic_c <- AICc(best_lb_model_rds_no_stadium)
adj_r_sq <- rsq::rsq(best_lb_model_rds_no_stadium, adj = T)
# create the table
table <- data.frame(Coefficient = coefficients, `Std. Error` = std_errors, `P-value` = pvalues, `z value` = z_score)
sapply(table, class)
table$Coefficient <- round(table$Coefficient.Estimate, 4)
table$StdError <- round(table$Coefficient.Std..Error, 4)
table$Pvalue <- format.pval(table$P.value, digits = 2)
table$z_score <-round(table$Coefficient.z.value, digits = 2)

table = table[,-c(1,2,3,4,5,6,7)]


table <- cbind(table, adjr2 = adj_r_sq, BIC = bic, AIC = aic, AICc = aic_c)




library(kableExtra)
# print the table
kable(table, caption = "Best Univariate (No Stadium) Lower Body Poisson Regression Model") %>%
  kable_styling()

```

# Best Home (No Stadium) Model

```{r}
home_best_overall = read_csv("final_files/game_injury_player_2019_2020_complete_update_vegas_weeks_bucketed_2.csv")

home_best_overall$weeks_bucketed = as.character(home_best_overall$weeks_bucketed)
home_best_overall$season = as.character(home_best_overall$season)


df_per_team = 
  home_best_overall %>% 
  na.omit() %>% 
  dplyr::group_by(game_id, home_team, away_team) %>% 
  dplyr::mutate(
    home_injury = dplyr::if_else(injured_team == home_team, T, F),
    away_injury = dplyr::if_else(injured_team == home_team, F, T)) %>% 
  dplyr::summarise(
    num_home_inj = sum(home_injury),
    num_away_inj = sum(away_injury)
  ) %>% 
  dplyr::ungroup() %>% 
  dplyr::left_join(
    y = home_best_overall |> dplyr::select(game_id, #num_injuries,
         #stadium, 
         dome, 
         surface_type,
         season,
         weeks_bucketed, distance_miles_home,distance_miles_away,
         HOME_day_since_last_game,AWAY_day_since_last_game,Avg_Feels_Like,
         Avg_Percipitation_Prob_Percent, Avg_Humidity_Percent,
         spread_line, total_line
    ),
    by = 'game_id'
  ) %>% 
  dplyr::select(-c(game_id)) %>% 
  unique()
  


home_poisson = glm(num_home_inj ~ . -away_team -home_team-num_away_inj -AWAY_day_since_last_game -distance_miles_away, data = df_per_team, na.action = na.fail, family="poisson")

# Examining goodness of fit
dredge_models_home = MuMIn::dredge(home_poisson)
all_models_home_overall = MuMIn::get.models(dredge_models_home, subset = T)
saveRDS(all_models_home_overall, "final_files/rds_models/all_models_home_overall_no_stadium.rds")

dredge_models_home$BIC = purrr::map_dbl(.x = all_models_home_overall, .f = BIC)
dredge_models_home$AIC = purrr::map_dbl(.x = all_models_home_overall, .f = AIC)
dredge_models_home$rsq =  purrr::map_dbl(.x = all_models_home_overall, .f = rsq::rsq, adj= T) 
which.min(dredge_models_home$BIC)
min(dredge_models_home$BIC) 
which.max(dredge_models_home$rsq)
max(dredge_models_home$rsq)

## should be based on the value from which.min(BIC)
best_home_model = MuMIn::get.models(dredge_models_home, subset = T)[[53]]
summary(best_home_model)
rsq::rsq(best_home_model, adj = T)
BIC(best_home_model)
pchisq(best_home_model$deviance, best_home_model$df.residual, lower.tail = FALSE)
saveRDS(best_home_model, file = "final_files/rds_models/best_home_model_no_stadium.rds")

best_home_model_rds_no_stadium = readRDS("final_files/rds_models/best_home_model_no_stadium.rds")
# extract the model summary information
best_home_model_summ_no_stadium <- summary(best_home_model_rds_no_stadium)
coefficients <- coef(best_home_model_summ_no_stadium)
pvalues <- summary(best_home_model_rds_no_stadium)$coefficients[, 4]
std_errors <- summary(best_home_model_rds_no_stadium)$coefficients[, 2]
z_score <- summary(best_home_model_rds_no_stadium)$coefficients[,3]
library(lmtest)
# add AIC, BIC, AICc and adj-R2
aic <- round(AIC(best_home_model_rds_no_stadium),4)
bic <- round(BIC(best_home_model_rds_no_stadium),4)
aic_c <- round(AICc(best_home_model_rds_no_stadium),4)
adj_r_sq <- round(rsq::rsq(best_home_model_rds_no_stadium, adj = T),4)
# create the table
table <- data.frame(Coefficient = coefficients, `Std. Error` = std_errors, `P-value` = pvalues, `z value` = z_score)
sapply(table, class)
table$Coefficient <- round(table$Coefficient.Estimate, 4)
table$StdError <- round(table$Coefficient.Std..Error, 4)
table$Pvalue <- format.pval(table$P.value, digits = 2)
table$z_score <-round(table$Coefficient.z.value, digits = 2)

table = table[,-c(1,2,3,4,5,6,7)]


table <- cbind(table, adjr2 = adj_r_sq, BIC = bic, AIC = aic, AICc = aic_c)




library(kableExtra)
# print the table
kable(table, caption = "Best Univariate (No Stadium) Home Poisson Regression Model") %>%
  kable_styling()

```

# Best Away (No Stadium) Model

```{r}
away_best_overall = read_csv("final_files/game_injury_player_2019_2020_complete_update_vegas_weeks_bucketed_2.csv")

away_best_overall$weeks_bucketed = as.character(away_best_overall$weeks_bucketed)
away_best_overall$season = as.character(away_best_overall$season)


df_per_team1 = 
  away_best_overall %>% 
  na.omit() %>% 
  dplyr::group_by(game_id, home_team, away_team) %>% 
  dplyr::mutate(
    home_injury = dplyr::if_else(injured_team == home_team, T, F),
    away_injury = dplyr::if_else(injured_team == home_team, F, T)) %>% 
  dplyr::summarise(
    num_home_inj = sum(home_injury),
    num_away_inj = sum(away_injury)
  ) %>% 
  dplyr::ungroup() %>% 
  dplyr::left_join(
    y = away_best_overall |> dplyr::select(game_id, #num_injuries,
         #stadium, 
         dome, 
         surface_type,
         season,
         weeks_bucketed, distance_miles_home,distance_miles_away,
         HOME_day_since_last_game,AWAY_day_since_last_game,Avg_Feels_Like,
         Avg_Percipitation_Prob_Percent, Avg_Humidity_Percent,
         spread_line, total_line
    ),
    by = 'game_id'
  ) %>% 
  dplyr::select(-c(game_id)) %>% 
  unique()
  


away_poisson = glm(num_away_inj ~ . -away_team -home_team -num_home_inj -HOME_day_since_last_game -distance_miles_home, data = df_per_team1, na.action = na.fail, family="poisson")

# Examining goodness of fit
dredge_models_away = MuMIn::dredge(away_poisson)
all_models_away_overall = MuMIn::get.models(dredge_models_away, subset = T)
saveRDS(all_models_away_overall, "final_files/rds_models/all_models_away_overall_no_stadium.rds")

dredge_models_away$BIC = purrr::map_dbl(.x = all_models_away_overall, .f = BIC)
dredge_models_away$AIC = purrr::map_dbl(.x = all_models_away_overall, .f = AIC)
dredge_models_away$rsq =  purrr::map_dbl(.x = all_models_away_overall, .f = rsq::rsq, adj= T) 
which.min(dredge_models_away$BIC)
min(dredge_models_away$BIC) #1475.925
which.max(dredge_models_away$rsq)
max(dredge_models_away$rsq) #0.10448

## should be based on the value from which.min(BIC)
best_away_model = MuMIn::get.models(dredge_models_away, subset = T)[[24]]
summary(best_away_model)
rsq::rsq(best_away_model, adj = T)
BIC(best_away_model)
pchisq(best_away_model$deviance, best_away_model$df.residual, lower.tail = FALSE)
saveRDS(best_away_model, file = "final_files/rds_models/best_away_model_no_stadium.rds")

best_away_model_rds_no_stadium = readRDS("final_files/rds_models/best_away_model_no_stadium.rds")
# extract the model summary information
best_away_model_summ_no_stadium <- summary(best_away_model_rds_no_stadium)
coefficients <- coef(best_away_model_summ_no_stadium)
pvalues <- summary(best_away_model_rds_no_stadium)$coefficients[, 4]
std_errors <- summary(best_away_model_rds_no_stadium)$coefficients[, 2]
z_score <- summary(best_away_model_rds_no_stadium)$coefficients[,3]
library(lmtest)
# add AIC, BIC, AICc and adj-R2
aic <- round(AIC(best_away_model_rds_no_stadium),4)
bic <- round(BIC(best_away_model_rds_no_stadium),4)
aic_c <- round(AICc(best_away_model_rds_no_stadium),4)
adj_r_sq <- round(rsq::rsq(best_away_model_rds_no_stadium, adj = T),4)
# create the table
table <- data.frame(Coefficient = coefficients, `Std. Error` = std_errors, `P-value` = pvalues, `z value` = z_score)
sapply(table, class)
table$Coefficient <- round(table$Coefficient.Estimate, 4)
table$StdError <- round(table$Coefficient.Std..Error, 4)
table$Pvalue <- format.pval(table$P.value, digits = 2)
table$z_score <-round(table$Coefficient.z.value, digits = 2)

table = table[,-c(1,2,3,4,5,6,7)]


table <- cbind(table, adjr2 = adj_r_sq, BIC = bic, AIC = aic, AICc = aic_c)




library(kableExtra)
# print the table
kable(table, caption = "Best Univariate (No Stadium) Away Poisson Regression Model") %>%
  kable_styling()
```

# Best Non-Contact Model

```{r}
df_nc = read_csv("final_files/game_injury_player_2019_2020_complete_update_vegas_weeks_bucketed_2_noncontact.csv")

df_nc$weeks_bucketed = as.character(df_nc$weeks_bucketed)
df_nc$season = as.character(df_nc$season)


df_nc_subset <- df_nc %>%  
  select(game_id, num_injuries,
         #stadium, 
         dome, 
         surface_type,
         season,
         weeks_bucketed, distance_miles_away,
         HOME_day_since_last_game,AWAY_day_since_last_game,Avg_Feels_Like,
         Avg_Percipitation_Prob_Percent, Avg_Humidity_Percent,
         spread_line, total_line) %>% 
  unique() %>% 
  mutate(num_injuries = as.integer(num_injuries))#,


df_nc_subset <- df_nc_subset %>% 
  select(-game_id) %>% 
  mutate_if(is.character, as.factor)

nc_poisson = glm(num_injuries ~ ., data = df_nc_subset, na.action = na.pass, family="poisson")
summary(nc_poisson)

# Examining goodness of fit
dredge_models_nc = MuMIn::dredge(nc_poisson)

all_models_nc = MuMIn::get.models(dredge_models_nc, subset = T)
saveRDS(all_models_nc, "final_files/rds_models/all_models_nc.rds")


dredge_models_nc$BIC = purrr::map_dbl(.x = all_models_nc, .f = BIC)
dredge_models_nc$AIC = purrr::map_dbl(.x = all_models_nc, .f = AIC)
dredge_models_nc$rsq =  purrr::map_dbl(.x = all_models_nc, .f = rsq::rsq, adj= T) 

dredge_models_nc %>% dplyr::arrange(desc(BIC)) %>% head()

which.min(dredge_models_nc$BIC)
min(dredge_models_nc$BIC)
max(dredge_models_nc$rsq)
which.max(dredge_models_nc$rsq)

best_nc_model = MuMIn::get.models(dredge_models_nc, subset = T)[[554]]
summary(best_nc_model)
rsq::rsq(best_nc_model, adj = T)
BIC(best_nc_model)
pchisq(best_nc_model$deviance, best_nc_model$df.residual, lower.tail = FALSE)
saveRDS(best_nc_model, file = "final_files/rds_models/best_nc_model_no_stadium.rds")

best_nc_model_rds = readRDS("final_files/rds_models/best_nc_model_no_stadium.rds")
# extract the model summary information
best_nc_model_summ <- summary(best_nc_model_rds)
coefficients <- coef(best_nc_model_summ)
pvalues <- summary(best_nc_model_rds)$coefficients[, 4]
std_errors <- summary(best_nc_model_rds)$coefficients[, 2]
z_score <- summary(best_nc_model_rds)$coefficients[,3]
library(lmtest)
# add AIC, BIC, AICc and adj-R2
aic <- AIC(best_nc_model_rds)
bic <- BIC(best_nc_model_rds)
aic_c <- AICc(best_nc_model_rds)
adj_r_sq <- rsq::rsq(best_nc_model_rds, adj = T)
# create the table
table <- data.frame(Coefficient = coefficients, `Std. Error` = std_errors, `P-value` = pvalues, `z value` = z_score)
sapply(table, class)
table$Coefficient <- round(table$Coefficient.Estimate, 4)
table$StdError <- round(table$Coefficient.Std..Error, 4)
table$Pvalue <- format.pval(table$P.value, digits = 2)
table$z_score <-round(table$Coefficient.z.value, digits = 2)

table = table[,-c(1,2,3,4,5,6,7)]


table <- cbind(table, adjr2 = adj_r_sq, BIC = bic, AIC = aic, AICc = aic_c)




library(kableExtra)
# print the table
kable(table, caption = "Best Univariate Non-Contact Poisson Regression Model") %>%
  kable_styling()
```

# Best Contact Model
```{r}
df_c = read_csv("final_files/game_injury_player_2019_2020_complete_update_vegas_weeks_bucketed_2_contact.csv")

df_c$weeks_bucketed = as.character(df_c$weeks_bucketed)
df_c$season = as.character(df_c$season)


df_c_subset <- df_c %>%  
  select(game_id, num_injuries,
         #stadium, 
         dome, 
         surface_type,
         season,
         weeks_bucketed, distance_miles_away,
         HOME_day_since_last_game,AWAY_day_since_last_game,Avg_Feels_Like,
         Avg_Percipitation_Prob_Percent, Avg_Humidity_Percent,
         spread_line, total_line) %>% 
  unique() %>% 
  mutate(num_injuries = as.integer(num_injuries))#,


df_c_subset <- df_c_subset %>% 
  select(-game_id) %>% 
  mutate_if(is.character, as.factor)

c_poisson = glm(num_injuries ~ ., data = df_c_subset, na.action = na.pass, family="poisson")
summary(c_poisson)

# Examining goodness of fit
dredge_models_c = MuMIn::dredge(c_poisson)

all_models_c = MuMIn::get.models(dredge_models_c, subset = T)
saveRDS(all_models_c, "final_files/rds_models/all_models_c.rds")


dredge_models_c$BIC = purrr::map_dbl(.x = all_models_c, .f = BIC)
dredge_models_c$AIC = purrr::map_dbl(.x = all_models_c, .f = AIC)
dredge_models_c$rsq =  purrr::map_dbl(.x = all_models_c, .f = rsq::rsq, adj= T) 

dredge_models_c %>% dplyr::arrange(desc(BIC)) %>% head()

which.min(dredge_models_c$BIC)
min(dredge_models_c$BIC)
max(dredge_models_c$rsq)
which.max(dredge_models_c$rsq)

best_c_model = MuMIn::get.models(dredge_models_c, subset = T)[[10]]
summary(best_c_model)
rsq::rsq(best_c_model,adj = T)
BIC(best_c_model)
pchisq(best_c_model$deviance, best_c_model$df.residual, lower.tail = FALSE)
saveRDS(best_c_model, file = "final_files/rds_models/best_c_model_no_stadium.rds")

best_c_model_rds = readRDS("final_files/rds_models/best_c_model_no_stadium.rds")
# extract the model summary information
best_c_model_summ <- summary(best_c_model_rds)
coefficients <- coef(best_c_model_summ)
pvalues <- summary(best_c_model_rds)$coefficients[, 4]
std_errors <- summary(best_c_model_rds)$coefficients[, 2]
z_score <- summary(best_c_model_rds)$coefficients[,3]
library(lmtest)
# add AIC, BIC, AICc and adj-R2
aic <- AIC(best_c_model_rds)
bic <- BIC(best_c_model_rds)
aic_c <- AICc(best_c_model_rds)
adj_r_sq <- rsq::rsq(best_c_model_rds, adj = T)
# create the table
table <- data.frame(Coefficient = coefficients, `Std. Error` = std_errors, `P-value` = pvalues, `z value` = z_score)
sapply(table, class)
table$Coefficient <- round(table$Coefficient.Estimate, 4)
table$StdError <- round(table$Coefficient.Std..Error, 4)
table$Pvalue <- format.pval(table$P.value, digits = 2)
table$z_score <-round(table$Coefficient.z.value, digits = 2)

table = table[,-c(1,2,3,4,5,6,7)]


table <- cbind(table, adjr2 = adj_r_sq, BIC = bic, AIC = aic, AICc = aic_c)




library(kableExtra)
# print the table
kable(table, caption = "Best Univariate Contact Poisson Regression Model") %>%
  kable_styling()
```